server:
  port: 8091

spring:
  application:
    name: Account
  datasource:
    name: account_schema
    url: jdbc:mysql://localhost:3306/account_schema
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



